-- Update faqs_page table with content
INSERT INTO faqs_page (id, question, answer, category) VALUES
(1, 'What services do you offer?', 'We offer a comprehensive range of educational services including academic tutoring, standardized test preparation, language learning, homeschooling support, and study coaching. Our services are designed to meet the unique needs of each student.', 'General'),
(2, 'How do I get started?', 'Getting started is easy! Simply browse our services, choose the one that best fits your needs, and click the "Get Started" button. You can also contact us directly through our contact form or by phone for personalized assistance.', 'General'),
(3, 'What are your qualifications?', 'Our team consists of highly qualified educators with extensive experience in their respective fields. All our tutors hold relevant degrees and certifications, and many have advanced degrees in their subjects.', 'General'),
(4, 'How much do your services cost?', 'Our pricing varies depending on the service and program you choose. We offer competitive rates and various packages to suit different budgets. Please visit our pricing page for detailed information.', 'Pricing'),
(5, 'Do you offer online tutoring?', 'Yes, we offer both in-person and online tutoring options. Our online platform provides the same high-quality education with the convenience of learning from anywhere.', 'Services'),
(6, 'What subjects do you cover?', 'We cover a wide range of subjects including Mathematics, Science, English, Languages, and standardized test preparation. Our subject coverage is comprehensive and can be tailored to specific needs.', 'Services'),
(7, 'How do you match students with tutors?', 'We carefully match students with tutors based on learning style, subject needs, and personality compatibility. This ensures the best possible learning experience for each student.', 'Services'),
(8, 'What is your cancellation policy?', 'We require 24 hours notice for cancellations. Late cancellations may be subject to a fee. Please refer to our terms and conditions for detailed information.', 'Policies'),
(9, 'Do you offer group sessions?', 'Yes, we offer both individual and group sessions. Group sessions can be a cost-effective option and provide opportunities for peer learning.', 'Services'),
(10, 'How do you track student progress?', 'We use a comprehensive progress tracking system that includes regular assessments, progress reports, and parent-teacher conferences to ensure students are meeting their learning goals.', 'Services');

-- Update faqs table with individual Q&A pairs
INSERT INTO faqs (id, question, answer, category) VALUES
(1, 'What is your teaching methodology?', 'Our teaching methodology is student-centered and adaptive. We focus on understanding each student\'s learning style and tailor our approach accordingly. We use a combination of direct instruction, interactive learning, and practical exercises to ensure effective learning.', 'Teaching'),
(2, 'How long are the tutoring sessions?', 'Standard tutoring sessions are 60 minutes long. However, we offer flexibility with 30-minute and 90-minute sessions available based on student needs and subject requirements.', 'Sessions'),
(3, 'Do you provide materials for the sessions?', 'Yes, we provide all necessary learning materials for our sessions. This includes worksheets, practice tests, and digital resources. Students are also given access to our online learning platform.', 'Resources'),
(4, 'What age groups do you work with?', 'We work with students of all ages, from elementary school through college. Our programs are specifically designed to meet the developmental needs of each age group.', 'General'),
(5, 'How do you handle different learning styles?', 'We assess each student\'s learning style and adapt our teaching methods accordingly. Whether a student is a visual, auditory, or kinesthetic learner, we ensure the material is presented in the most effective way for them.', 'Teaching'),
(6, 'What is your policy on homework help?', 'We provide homework help as part of our tutoring services. Our tutors can assist with understanding concepts, checking work, and providing guidance, while ensuring students develop independent learning skills.', 'Services'),
(7, 'Do you offer summer programs?', 'Yes, we offer specialized summer programs that include intensive courses, review sessions, and preparation for the upcoming school year.', 'Programs'),
(8, 'How do you communicate with parents?', 'We maintain regular communication with parents through progress reports, parent-teacher meetings, and our online portal where parents can track their child\'s progress.', 'Communication'),
(9, 'What is your approach to test preparation?', 'Our test preparation approach combines content review, strategy development, and practice tests. We focus on both subject knowledge and test-taking skills.', 'Testing'),
(10, 'Do you offer scholarships or financial aid?', 'Yes, we offer various scholarship programs and financial aid options to make our services accessible to all students. Please contact us for more information about eligibility and application process.', 'Financial'); 